# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p ${MYSQL_PASSWORD}"]
      # test: >
      #   CMD bash -c 'mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}'
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - ${MYSQL_PORTS}
    # volumes:
    #   - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
      # - tunnel

  app:
    build: .
    container_name: kp-golang-mysql2-container
    restart: always
    depends_on:
      # - mysql
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: mrg
      DB_PASSWORD: 123123123
      DB_NAME: cerdikia
    ports:
      - "80:80"
    networks:
      - mynetwork
      # - tunnel

  migrate:
    image: migrate/migrate
    container_name: migration
    # restart: always
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "mysql://mrg:123123123@tcp(mysql:3306)/cerdikia", "up" ]
    depends_on:
    # - mysql
      mysql:
        condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
    driver: local